/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      fontFamily: {
        sans: ['Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        serif: ['Trajan Pro', 'Trajan', 'Times New Roman', 'serif'],
        ar: ['GE SS Two', 'Adobe Arabic', 'Segoe UI', 'Tahoma', 'sans-serif'],
      },
      colors: {
        primary: {
          50: 'rgb(var(--myghf-primary-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-primary-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-primary-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-primary-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-primary-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-primary-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-primary-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-primary-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-primary-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-primary-900) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--myghf-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-secondary-900) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--myghf-success-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-success-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-success-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-success-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-success-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-success-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-success-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-success-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-success-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-success-900) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--myghf-warning-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-warning-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-warning-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-warning-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-warning-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-warning-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-warning-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-warning-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-warning-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-warning-900) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--myghf-error-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-error-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-error-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-error-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-error-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-error-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-error-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-error-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-error-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-error-900) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--myghf-info-50) / <alpha-value>)',
          100: 'rgb(var(--myghf-info-100) / <alpha-value>)',
          200: 'rgb(var(--myghf-info-200) / <alpha-value>)',
          300: 'rgb(var(--myghf-info-300) / <alpha-value>)',
          400: 'rgb(var(--myghf-info-400) / <alpha-value>)',
          500: 'rgb(var(--myghf-info-500) / <alpha-value>)',
          600: 'rgb(var(--myghf-info-600) / <alpha-value>)',
          700: 'rgb(var(--myghf-info-700) / <alpha-value>)',
          800: 'rgb(var(--myghf-info-800) / <alpha-value>)',
          900: 'rgb(var(--myghf-info-900) / <alpha-value>)',
        },
        background: 'rgb(var(--myghf-background) / <alpha-value>)',
        foreground: 'rgb(var(--myghf-foreground) / <alpha-value>)',
        surface: 'rgb(var(--myghf-surface) / <alpha-value>)',
        'surface-muted': 'rgb(var(--myghf-surface-muted) / <alpha-value>)',
        border: 'rgb(var(--myghf-border) / <alpha-value>)',
        muted: 'rgb(var(--myghf-muted) / <alpha-value>)',
        grey: 'rgb(var(--myghf-muted) / <alpha-value>)',
      },
      boxShadow: {
        popover: '0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        dialog: '0 20px 25px -5px rgb(0 0 0 / 0.25)',
      },
    },
  },
}