/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50: 'rgb(var(--ahc-primary-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-primary-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-primary-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-primary-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-primary-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-primary-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-primary-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-primary-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-primary-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-primary-900) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--ahc-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-secondary-900) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--ahc-success-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-success-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-success-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-success-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-success-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-success-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-success-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-success-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-success-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-success-900) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--ahc-warning-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-warning-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-warning-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-warning-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-warning-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-warning-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-warning-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-warning-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-warning-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-warning-900) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--ahc-error-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-error-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-error-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-error-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-error-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-error-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-error-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-error-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-error-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-error-900) / <alpha-value>)',
        },
        info: {
          50: 'rgb(var(--ahc-info-50) / <alpha-value>)',
          100: 'rgb(var(--ahc-info-100) / <alpha-value>)',
          200: 'rgb(var(--ahc-info-200) / <alpha-value>)',
          300: 'rgb(var(--ahc-info-300) / <alpha-value>)',
          400: 'rgb(var(--ahc-info-400) / <alpha-value>)',
          500: 'rgb(var(--ahc-info-500) / <alpha-value>)',
          600: 'rgb(var(--ahc-info-600) / <alpha-value>)',
          700: 'rgb(var(--ahc-info-700) / <alpha-value>)',
          800: 'rgb(var(--ahc-info-800) / <alpha-value>)',
          900: 'rgb(var(--ahc-info-900) / <alpha-value>)',
        },
        background: 'rgb(var(--ahc-background) / <alpha-value>)',
        foreground: 'rgb(var(--ahc-foreground) / <alpha-value>)',
        surface: 'rgb(var(--ahc-surface) / <alpha-value>)',
        'surface-muted': 'rgb(var(--ahc-surface-muted) / <alpha-value>)',
        border: 'rgb(var(--ahc-border) / <alpha-value>)',
        muted: 'rgb(var(--ahc-muted) / <alpha-value>)',
        grey: 'rgb(var(--ahc-muted) / <alpha-value>)',
      },
      boxShadow: {
        popover: '0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        dialog: '0 20px 25px -5px rgb(0 0 0 / 0.25)',
      },
    },
  },
}